# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_exportgridplot.ui'
#
# Created: Sun Sep 11 21:57:32 2011
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_ExportGridPlot(object):
    def setupUi(self, ExportGridPlot):
        ExportGridPlot.setObjectName("ExportGridPlot")
        ExportGridPlot.resize(349, 266)
        self.gridLayout_3 = QtGui.QGridLayout(ExportGridPlot)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox = QtGui.QGroupBox(ExportGridPlot)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.cBLayer = QtGui.QComboBox(self.groupBox)
        self.cBLayer.setMinimumSize(QtCore.QSize(0, 23))
        self.cBLayer.setObjectName("cBLayer")
        self.gridLayout.addWidget(self.cBLayer, 0, 1, 1, 1)
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.cBGridPoints = QtGui.QCheckBox(self.groupBox)
        self.cBGridPoints.setMinimumSize(QtCore.QSize(0, 23))
        self.cBGridPoints.setText("")
        self.cBGridPoints.setChecked(True)
        self.cBGridPoints.setObjectName("cBGridPoints")
        self.gridLayout.addWidget(self.cBGridPoints, 3, 1, 1, 1)
        self.cBTriangles = QtGui.QCheckBox(self.groupBox)
        self.cBTriangles.setMinimumSize(QtCore.QSize(0, 23))
        self.cBTriangles.setText("")
        self.cBTriangles.setChecked(True)
        self.cBTriangles.setObjectName("cBTriangles")
        self.gridLayout.addWidget(self.cBTriangles, 1, 1, 1, 1)
        self.cBCornerPoints = QtGui.QCheckBox(self.groupBox)
        self.cBCornerPoints.setMinimumSize(QtCore.QSize(0, 23))
        self.cBCornerPoints.setText("")
        self.cBCornerPoints.setChecked(True)
        self.cBCornerPoints.setObjectName("cBCornerPoints")
        self.gridLayout.addWidget(self.cBCornerPoints, 2, 1, 1, 1)
        self.sBGridDistance = QtGui.QDoubleSpinBox(self.groupBox)
        self.sBGridDistance.setMinimumSize(QtCore.QSize(0, 23))
        self.sBGridDistance.setPrefix("")
        self.sBGridDistance.setMaximum(100000000.0)
        self.sBGridDistance.setSingleStep(1.0)
        self.sBGridDistance.setProperty("value", 100.0)
        self.sBGridDistance.setObjectName("sBGridDistance")
        self.gridLayout.addWidget(self.sBGridDistance, 4, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1)
        self.cBAddLayers = QtGui.QCheckBox(self.groupBox)
        self.cBAddLayers.setMinimumSize(QtCore.QSize(0, 23))
        self.cBAddLayers.setText("")
        self.cBAddLayers.setChecked(True)
        self.cBAddLayers.setObjectName("cBAddLayers")
        self.gridLayout.addWidget(self.cBAddLayers, 5, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox, 0, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(ExportGridPlot)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_3.addWidget(self.buttonBox, 1, 0, 1, 1)

        self.retranslateUi(ExportGridPlot)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), ExportGridPlot.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), ExportGridPlot.reject)
        QtCore.QMetaObject.connectSlotsByName(ExportGridPlot)

    def retranslateUi(self, ExportGridPlot):
        ExportGridPlot.setWindowTitle(QtGui.QApplication.translate("ExportGridPlot", "Export Grid Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("ExportGridPlot", "Create regular grid plot ", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("ExportGridPlot", "Perimeter: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("ExportGridPlot", "Triangles:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("ExportGridPlot", "Corner points:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("ExportGridPlot", "Grid points: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("ExportGridPlot", "Grid distance:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("ExportGridPlot", "Add layers to map:", None, QtGui.QApplication.UnicodeUTF8))

