# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_settings.ui'
#
# Created: Sun Jul 31 10:22:46 2011
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Settings(object):
    def setupUi(self, Settings):
        Settings.setObjectName("Settings")
        Settings.resize(541, 403)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Settings.sizePolicy().hasHeightForWidth())
        Settings.setSizePolicy(sizePolicy)
        self.gridLayout = QtGui.QGridLayout(Settings)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonBox = QtGui.QDialogButtonBox(Settings)
        self.buttonBox.setEnabled(True)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 3, 0, 1, 1)
        self.tabWidget = QtGui.QTabWidget(Settings)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideLeft)
        self.tabWidget.setObjectName("tabWidget")
        self.tabProvider = QtGui.QWidget()
        self.tabProvider.setObjectName("tabProvider")
        self.gridLayout_11 = QtGui.QGridLayout(self.tabProvider)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.groupBox_3 = QtGui.QGroupBox(self.tabProvider)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.formLayout_3 = QtGui.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.radioButtonProviderDatabase = QtGui.QRadioButton(self.groupBox_3)
        self.radioButtonProviderDatabase.setChecked(True)
        self.radioButtonProviderDatabase.setObjectName("radioButtonProviderDatabase")
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.radioButtonProviderDatabase)
        self.radioButtonProviderWfs = QtGui.QRadioButton(self.groupBox_3)
        self.radioButtonProviderWfs.setObjectName("radioButtonProviderWfs")
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.radioButtonProviderWfs)
        self.gridLayout_4.addLayout(self.formLayout_3, 0, 0, 1, 1)
        self.gridLayout_11.addWidget(self.groupBox_3, 0, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_11.addItem(spacerItem, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tabProvider, "")
        self.tabDatabase = QtGui.QWidget()
        self.tabDatabase.setEnabled(True)
        self.tabDatabase.setObjectName("tabDatabase")
        self.gridLayout_2 = QtGui.QGridLayout(self.tabDatabase)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.scrollArea = QtGui.QScrollArea(self.tabDatabase)
        self.scrollArea.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea.setFrameShadow(QtGui.QFrame.Raised)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtGui.QWidget(self.scrollArea)
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 501, 302))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_5 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.groupBox = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout.setObjectName("formLayout")
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_5)
        self.lineEditDbHost = QtGui.QLineEdit(self.groupBox)
        self.lineEditDbHost.setObjectName("lineEditDbHost")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEditDbHost)
        self.lineEditDbDatabase = QtGui.QLineEdit(self.groupBox)
        self.lineEditDbDatabase.setObjectName("lineEditDbDatabase")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEditDbDatabase)
        self.lineEditDbPort = QtGui.QLineEdit(self.groupBox)
        self.lineEditDbPort.setObjectName("lineEditDbPort")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEditDbPort)
        self.lineEditDbSchema = QtGui.QLineEdit(self.groupBox)
        self.lineEditDbSchema.setObjectName("lineEditDbSchema")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineEditDbSchema)
        self.lineEditDbUsername = QtGui.QLineEdit(self.groupBox)
        self.lineEditDbUsername.setObjectName("lineEditDbUsername")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.lineEditDbUsername)
        self.lineEditDbPassword = QtGui.QLineEdit(self.groupBox)
        self.lineEditDbPassword.setEchoMode(QtGui.QLineEdit.PasswordEchoOnEdit)
        self.lineEditDbPassword.setObjectName("lineEditDbPassword")
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.lineEditDbPassword)
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_6)
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_7)
        self.lineEditDbAdmin = QtGui.QLineEdit(self.groupBox)
        self.lineEditDbAdmin.setObjectName("lineEditDbAdmin")
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.lineEditDbAdmin)
        self.lineEditDbAdminPassword = QtGui.QLineEdit(self.groupBox)
        self.lineEditDbAdminPassword.setEchoMode(QtGui.QLineEdit.PasswordEchoOnEdit)
        self.lineEditDbAdminPassword.setObjectName("lineEditDbAdminPassword")
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.lineEditDbAdminPassword)
        self.label_9 = QtGui.QLabel(self.groupBox)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_9)
        self.gridLayout_3.addLayout(self.formLayout, 1, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabDatabase, "")
        self.tabWfs = QtGui.QWidget()
        self.tabWfs.setObjectName("tabWfs")
        self.gridLayout_7 = QtGui.QGridLayout(self.tabWfs)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.scrollArea_2 = QtGui.QScrollArea(self.tabWfs)
        self.scrollArea_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea_2.setFrameShadow(QtGui.QFrame.Plain)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtGui.QWidget(self.scrollArea_2)
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 501, 302))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_9 = QtGui.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.groupBox_2 = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_8 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_8)
        self.lineEditWfsUrl = QtGui.QLineEdit(self.groupBox_2)
        self.lineEditWfsUrl.setObjectName("lineEditWfsUrl")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEditWfsUrl)
        self.label_11 = QtGui.QLabel(self.groupBox_2)
        self.label_11.setObjectName("label_11")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_11)
        self.label_12 = QtGui.QLabel(self.groupBox_2)
        self.label_12.setObjectName("label_12")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_12)
        self.label_13 = QtGui.QLabel(self.groupBox_2)
        self.label_13.setObjectName("label_13")
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_13)
        self.lineEditWfsNamespace = QtGui.QLineEdit(self.groupBox_2)
        self.lineEditWfsNamespace.setObjectName("lineEditWfsNamespace")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEditWfsNamespace)
        self.lineEditWfsUsername = QtGui.QLineEdit(self.groupBox_2)
        self.lineEditWfsUsername.setObjectName("lineEditWfsUsername")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEditWfsUsername)
        self.lineEditWfsPassword = QtGui.QLineEdit(self.groupBox_2)
        self.lineEditWfsPassword.setEchoMode(QtGui.QLineEdit.PasswordEchoOnEdit)
        self.lineEditWfsPassword.setObjectName("lineEditWfsPassword")
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineEditWfsPassword)
        self.gridLayout_8.addLayout(self.formLayout_2, 0, 0, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_7.addWidget(self.scrollArea_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabWfs, "")
        self.tabData = QtGui.QWidget()
        self.tabData.setObjectName("tabData")
        self.gridLayout_6 = QtGui.QGridLayout(self.tabData)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.groupBox_4 = QtGui.QGroupBox(self.tabData)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_10 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_10 = QtGui.QLabel(self.groupBox_4)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_2.addWidget(self.label_10)
        self.lineEditTempDir = QtGui.QLineEdit(self.groupBox_4)
        self.lineEditTempDir.setObjectName("lineEditTempDir")
        self.horizontalLayout_2.addWidget(self.lineEditTempDir)
        self.btnBrowseTempDir = QtGui.QPushButton(self.groupBox_4)
        self.btnBrowseTempDir.setObjectName("btnBrowseTempDir")
        self.horizontalLayout_2.addWidget(self.btnBrowseTempDir)
        self.gridLayout_10.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_4, 0, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem1, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tabData, "")
        self.gridLayout.addWidget(self.tabWidget, 1, 0, 1, 1)

        self.retranslateUi(Settings)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), Settings.reject)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), Settings.accept)
        QtCore.QMetaObject.connectSlotsByName(Settings)

    def retranslateUi(self, Settings):
        Settings.setWindowTitle(QtGui.QApplication.translate("Settings", " Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Settings", "Choose provider ", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonProviderDatabase.setText(QtGui.QApplication.translate("Settings", "Database", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonProviderWfs.setText(QtGui.QApplication.translate("Settings", "WFS", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabProvider), QtGui.QApplication.translate("Settings", "Provider", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Settings", "Connection parameter", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Settings", "Host", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Settings", "Database", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Settings", "Port", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Settings", "Username", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Settings", "User password", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Settings", "Admin", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Settings", "Admin password", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Settings", "Schema", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabDatabase), QtGui.QApplication.translate("Settings", "Database", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Settings", "Connection parameters ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Settings", "URL ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Settings", "Namespace ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Settings", "Username", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Settings", "User password", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWfs), QtGui.QApplication.translate("Settings", "WFS", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("Settings", "Temporary Data", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Settings", "Directory: ", None, QtGui.QApplication.UnicodeUTF8))
        self.btnBrowseTempDir.setText(QtGui.QApplication.translate("Settings", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabData), QtGui.QApplication.translate("Settings", "Data", None, QtGui.QApplication.UnicodeUTF8))

